group=io.github.danielliu1123
version=1.0.0-SNAPSHOT

# https://plugins.gradle.org/plugin/com.gradle.plugin-publish
gradlePublishPluginVersion=2.1.1

# Code quality
# https://plugins.gradle.org/plugin/com.diffplug.spotless
spotlessVersion=8.4.0
# https://plugins.gradle.org/plugin/com.github.spotbugs
spotbugsVersion=6.5.1

org.gradle.jvmargs=-Xmx2g
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
